using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class RoleSetupGuiSavePanel : DefaultWindow
{
    public RoleSetupGuiSavePanel()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ =>
        {
            Close();
        };

        CloseButton.Visible = false;
    }
}
