using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI.Roles;

/// <summary>
/// A nice job label and a button for setting that job's loadout
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LoadoutControl : BoxContainer
{
    private List<ProtoId<GuideEntryPrototype>>? _guides;

    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    public LoadoutControl()
    {
        RobustXamlLoader.Load(this);

        Help.OnPressed += _ =>
        {
            if (_guides != null)
                OnOpenGuidebook?.Invoke(_guides);
        };
    }

    /// <summary>
    /// Actually adds the controls.
    /// </summary>
    public void Setup(
        string title,
        int titleSize,
        string? description,
        TextureRect? icon = null,
        List<ProtoId<GuideEntryPrototype>>? guides = null)
    {
        Help.Visible = guides != null;
        _guides = guides;

        TitleLabel.Text = title;
        TitleLabel.MinSize = new Vector2(titleSize, 0f);
        TitleLabel.ToolTip = description;

        if (icon != null)
        {
            AddChild(icon);
            icon.SetPositionFirst();
        }
    }
}
